### PR TITLE
Changed building_id in example to be a string

### PR DESCRIPTION
**Pull request by RobinsonMann**
The API actually returns

```json

},
  "data":{
    "building_id":"23",
    "building_code":"MHR",
    "building_name":"Minota Hagey Residence",
    "alternate_names":[
      "Velocity"
    ],
    "latitude":43.46579535,
    "longitude":-80.54275113,
    "building_sections":[
      
    ],
    "building_outline":[
      
    ]
  }

```

Unsure if other files need to be changed or not.

### CODE REVIEW

**Comment by KartikTalwar** [comment]
it should be a string. feel free to merge!

**Comment by RobinsonMann** [comment]
Sounds good ! Thanks

**Comment by RobinsonMann** [comment]
Sounds good! I'm not sure if I am able to tho. At the bottom of comment section it says "Only those with write access to this repository can merge pull requests." Maybe the button is on another page, not quite sure tbh.

**Comment by KartikTalwar** [comment]
You need to go to http://github.com/uwaterloo to accept your invitation first and you should be able to merge after that

**Comment by RobinsonMann** [comment]
Hahaha sorry about that. Thanks for taking the time to help me out :)

**Pull request merged**
