### PR TITLE
resolve #55 Add Add /v2/services/[site].{format} Documentation

### LINKED ISSUE #55: Add /v2/services/[site].{format} Documentation

### PR DESCRIPTION
**Pull request by nathanv**

### CODE REVIEW

**Comment by nathanv** [comment]
@RobinsonMann Would you like to do review on this new doc?

**Comment by nathanv** [comment]
Just realized that I need to edit https://github.com/uWaterloo/api-documentation/blob/55/README.md

**Comment by nathanv** [comment]
@KartikTalwar Can you review this?

**Comment by KartikTalwar** [comment]
@nathanv this looks good to me. Feel free to merge

**Pull request merged**
